#!/bin/bash 
#PBS -N snap_openmp
#PBS -l nodes=1:ppn=16:xeon-phi,walltime=01:00:00
#PBS -q testq
#PBS -o OUT
#PBS -j oe

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE > machine.file.$PBS_JOBID

make clean && make

source src.sh
export MIC_ENV_PREFIX=MIC
export KMP_AFFINITY=compact
export OMP_NUM_THREADS=16
export MIC_OMP_NUM_THREADS=236
export MIC_KMP_AFFINITY=compact
export OFFLOAD_REPORT= 

snap snap.in snap.out
